cpweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('polls/', include('polls.urls')),
    path('', include('elections.urls')),
    path('admin/', admin.site.urls),
]

elections/urls.py
from django.urls import path, include
from . import views

app_name = 'elections'
urlpatterns = [
    path('', views.index, name='home'),
    path('areas/<str:area>/', views.areas),
    path('areas/<str:area>/results/', views.results),
    path('polls/<int:poll_id>/', views.polls),
    path('candidates/<str:name>/', views.candidates),
]

cp/models.py
from django.db import models

# Create your models here.

elections/models.py
from django.db import models


# Create your models here.
class Candidate(models.Model):
    name = models.CharField(max_length=10)
    introduction = models.TextField()
    area = models.CharField(max_length=15)
    party_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Poll(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    area = models.CharField(max_length=15)

    def __str__(self):
        return "{} {}.{}~{}.{}".format(self.area,
                                       self.start_date.month,
                                       self.start_date.day,
                                       self.end_date.month,
                                       self.end_date.day,
                                       )


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} {} :: {}".format(self.poll,
                                 self.candidate,
                                 self.votes)

cp/views.py
from django.shortcuts import render

# Create your views here.

elections/views.py
from django.shortcuts import (render,
                              get_object_or_404,
                              )
from django.http import (HttpResponse,
                         HttpResponseRedirect,
                         HttpResponseNotFound,
                         Http404,
                         )

from .models import Candidate, Poll, Choice

import datetime
from django.db.models import Sum


# Create your views here.

def index(request):
    candidates = Candidate.objects.all()

    context = {'candidates': candidates}
    return render(request, 'elections/index.html', context)


def candidates(request, name):
    candidate = get_object_or_404(Candidate, name=name)

    # try:
    #     candidate = Candidate.objects.get(name=name)
    # except:
    #     raise Http404
    return HttpResponse(candidate.name)


def areas(request, area):
    today = datetime.datetime.now()
    try:
        poll = Poll.objects.get(area=area,
                                start_date__lte=today,
                                end_date__gte=today)
        candidates = Candidate.objects.filter(area=area)
    except:
        poll = None
        candidates = None
    context = {'candidates': candidates,
               'area': area,
               'poll': poll}
    return render(request, 'elections/area.html', context)


def polls(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    selection = request.POST['choice']

    try:
        choice = Choice.objects.get(poll_id=poll_id,
                                    candidate_id=selection
                                    )
        choice.votes += 1
        choice.save()
    except:
        choice = Choice(poll_id=poll_id, candidate_id=selection, votes=1)
        choice.save()

    return HttpResponseRedirect("/areas/{}/results/".format(poll.area))


def results(request, area):
    candidates = Candidate.objects.filter(area=area)
    polls = Poll.objects.filter(area=area)
    poll_result = []
    for poll in polls:
        result = {}
        result['start_date'] = poll.start_date
        result['end_date'] = poll.end_date
        total_votes = Choice.objects.filter(poll_id=poll.id).aggregate(Sum('votes'))
        result['total_votes'] = total_votes['votes__sum']
        rates = []
        for candidate in candidates:
            try:
                choice = Choice.objects.get(poll_id=poll.id, candidate_id=candidate.id)
                rates.append(
                    round((choice.votes * 100 / result['total_votes']), 1))
            except:
                rates.append(0)
        result['rates'] = rates
        poll_result.append(result)

    context = {'candidates': candidates, 'area': area, 'poll_result': poll_result}

    return render(request, 'elections/result.html', context)

cp/templates/cp/area.html
{% extends "elections/layout.html" %}

{% block title%}
{{area}}
{% endblock %}

{% block content%}
<div class="container">
    <h1>{{area}}</h1>
    <br>
    {% if poll %}
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>기호</B></td>
            <td><B>지지하기</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
        <tr>
            <td> {{candidate.name}}</td>
            <td> {{candidate.introduction}}</td>
            <td> 기호{{candidate.party_number}}번</td>
            <td>
                <form action="/polls/{{poll.id}}/" method="post">
                    {% csrf_token %}
                    <button name="choice" value="{{candidate.id}}">선택</button>
                </form>
            </td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
    {% else %}
    여론조사가 없습니다
    {% endif %}
</div>
{% endblock %}

cp/templates/cp/index.html
{% extends "elections/layout.html" %}

{% block title%}
선거 후보12
{% endblock %}

{% block content%}
<body>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>출마지역</B></td>
            <td><B>기호</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
        <tr>
            <td>{{candidate.name}}</td>
            <td>{{candidate.introduction}}</td>
            <td><a href="areas/{{candidate.area}}/">{{candidate.area}}</a></td>
            <td>기호{{candidate.party_number}}번</td>
        </tr>
        {% endfor%}

        <tbody>
    </table>
</body>
{% endblock %}

cp/templates/cp/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'elections/test_img.ico' %}"/>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'elections:home'%}">사이트명</a>
        </div>
</nav>

{% block content %}{% endblock %}
</body>
</html>

cp/templates/cp/result.html
{% extends "elections/layout.html" %}

{% block title%}
{{area}} 여론조사 결과
{% endblock %}

{% block content%}

<div class="container">
    <h1>{{area}}</h1>
    <br>
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>기간</B></td>
            {% for candidate in candidates %}
            <td><B>{{candidate.name}}</B></td>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for result in poll_result %}
        <tr>
            <td> {{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}}
                ~ {{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}}
            </td>
            {% for rate in result.rates %}
            <td> {{rate}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        <tbody>
    </table>
</div>
{% endblock %}

elections/templates/elections/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">


    <!--<title>Hello, world!</title>-->
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Page 1</a></li>
            <li><a href="#">Page 2</a></li>
        </ul>
        <form class="navbar-form navbar-left" action="/action_page.php">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
    </div>
</nav>
<!--<h1>Hello, world!</h1>-->

<button type="button" class="btn">Basic</button>
<button type="button" class="btn btn-default">Default</button>
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-link">Link</button>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block content %}{% endblock %}
</dev>
</body>
</html>